services:
  report-db:
    image: postgres:15
    container_name: engagement-db
    restart: always
    environment:
      POSTGRES_DB: engagement_service_db
      POSTGRES_USER: engagement_user
      POSTGRES_PASSWORD: engagement_pass
    ports:
      - "5432:5432"
    volumes:
      - engagement_db_data:/var/lib/postgresql/data

volumes:
  engagement_db_data: